name: Format
# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.ACCESS_TOKEN }}
            - uses: actions/setup-node@v2
              with:
                  node-version: '14.x'
            - run: npm ci
            - run: npm run prettier
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: ':art: apply prettier formatting'
                  branch: ${{ github.head_ref }}
